// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_IT_-KwK4m2dV3jLZSqkPDZm4rAZTuX4',
    appId: '1:267000810466:web:3bccc921d4985affcc07bb',
    messagingSenderId: '267000810466',
    projectId: 'phuclong-tea-8891',
    authDomain: 'phuclong-tea-8891.firebaseapp.com',
    storageBucket: 'phuclong-tea-8891.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_IT_-KwK4m2dV3jLZSqkPDZm4rAZTuX4',
    appId: '1:267000810466:web:18a222f704da4c26cc07bb',
    messagingSenderId: '267000810466',
    projectId: 'phuclong-tea-8891',
    authDomain: 'phuclong-tea-8891.firebaseapp.com',
    storageBucket: 'phuclong-tea-8891.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2s4EDU0dmieOHU9bDK3gAFGPdfdI-QY4',
    appId: '1:267000810466:ios:6be262eae2e98368cc07bb',
    messagingSenderId: '267000810466',
    projectId: 'phuclong-tea-8891',
    storageBucket: 'phuclong-tea-8891.firebasestorage.app',
    iosBundleId: 'com.dkhang.plapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2s4EDU0dmieOHU9bDK3gAFGPdfdI-QY4',
    appId: '1:267000810466:ios:6be262eae2e98368cc07bb',
    messagingSenderId: '267000810466',
    projectId: 'phuclong-tea-8891',
    storageBucket: 'phuclong-tea-8891.firebasestorage.app',
    iosBundleId: 'com.dkhang.plapp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeKUH3OXWVLzQoRfjuV9Atoh_fxdp5q5k',
    appId: '1:267000810466:android:882c48efc13c4531cc07bb',
    messagingSenderId: '267000810466',
    projectId: 'phuclong-tea-8891',
    storageBucket: 'phuclong-tea-8891.firebasestorage.app',
  );
}

